"""
Phase 16 - LLM Guided Intelligence ⭐⭐⭐⭐⭐

This is where the project becomes an AI assistant.

User asks: "Find the man wearing the red cap near the entrance."

The LLM should not generate SQL. Instead it generates a plan.

Example:
{
  "object": "person",
  "attributes": {
    "headwear": "red cap"
  },
  "actions": [
    "search_embeddings",
    "search_events", 
    "build_timeline",
    "retrieve_clips"
  ]
}

Your backend executes this plan.
"""

import json
import logging
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional
from dataclasses import dataclass
from enum import Enum

logger = logging.getLogger(__name__)


class ActionType(Enum):
    """Available action types for LLM plans"""
    SEARCH_EMBEDDINGS = "search_embeddings"
    SEARCH_EVENTS = "search_events"
    SEARCH_TEXT = "search_text"
    SEARCH_TIME_RANGE = "search_time_range"
    BUILD_TIMELINE = "build_timeline"
    RETRIEVE_CLIPS = "retrieve_clips"
    ANALYZE_MOVEMENT = "analyze_movement"
    FIND_SIMILAR = "find_similar"
    COUNT_OBJECTS = "count_objects"
    TRACK_DURATION = "track_duration"


@dataclass
class SearchPlan:
    """Structured plan generated by LLM"""
    query_type: str
    primary_object: str
    attributes: Dict[str, Any]
    temporal_constraints: Dict[str, Any]
    spatial_constraints: Dict[str, Any]
    actions: List[ActionType]
    confidence: float
    reasoning: str


class LLMIntelligence:
    """
    LLM-guided intelligence for investigation queries.
    
    This service:
    1. Parses natural language queries
    2. Generates structured execution plans
    3. Never touches the database directly
    4. Isolates LLM from data layer
    5. Provides explainable AI reasoning
    """
    
    def __init__(self, use_mock_llm: bool = True):
        """
        Initialize LLM intelligence service
        
        Args:
            use_mock_llm: Whether to use mock LLM (True) or real LLM (False)
        """
        self.use_mock_llm = use_mock_llm
        self.query_templates = self._load_query_templates()
        
        if not use_mock_llm:
            # In production, initialize actual LLM client here
            # self.llm_client = OpenAI(api_key=settings.OPENAI_API_KEY)
            logger.info("🤖 LLM Intelligence initialized with real LLM")
        else:
            logger.info("🤖 LLM Intelligence initialized with mock LLM")
    
    def parse_query(self, user_query: str, context: Optional[Dict] = None) -> SearchPlan:
        """
        Parse natural language query into structured execution plan
        
        Args:
            user_query: Natural language query from user
            context: Optional context (video_id, time_range, etc.)
            
        Returns:
            Structured search plan for execution
        """
        logger.info(f"🧠 Parsing query: '{user_query}'")
        
        if self.use_mock_llm:
            plan = self._mock_llm_parse(user_query, context)
        else:
            plan = self._real_llm_parse(user_query, context)
        
        logger.info(f"✅ Generated plan: {plan.query_type} with {len(plan.actions)} actions")
        return plan
    
    def _mock_llm_parse(self, user_query: str, context: Optional[Dict] = None) -> SearchPlan:
        """
        Mock LLM implementation for development and testing
        
        Args:
            user_query: User's natural language query
            context: Optional context
            
        Returns:
            Structured search plan
        """
        query_lower = user_query.lower()
        
        # Person with clothing/attributes queries
        if "person" in query_lower or "man" in query_lower or "woman" in query_lower:
            return self._parse_person_query(user_query, query_lower, context)
        
        # Time-based queries
        elif "after" in query_lower or "before" in query_lower or "between" in query_lower:
            return self._parse_time_query(user_query, query_lower, context)
        
        # Duration queries
        elif "stayed" in query_lower or "more than" in query_lower or "longer" in query_lower:
            return self._parse_duration_query(user_query, query_lower, context)
        
        # Movement queries
        elif "entered" in query_lower or "exited" in query_lower or "moved" in query_lower:
            return self._parse_movement_query(user_query, query_lower, context)
        
        # Counting queries
        elif "how many" in query_lower or "count" in query_lower or "number of" in query_lower:
            return self._parse_counting_query(user_query, query_lower, context)
        
        # General search fallback
        else:
            return self._parse_general_query(user_query, query_lower, context)
    
    def _parse_person_query(self, original_query: str, query_lower: str, context: Optional[Dict]) -> SearchPlan:
        """Parse person-focused queries"""
        
        # Extract attributes
        attributes = {}
        
        # Clothing colors
        colors = ["red", "blue", "green", "black", "white", "yellow", "orange", "purple", "pink", "brown", "gray"]
        for color in colors:
            if color in query_lower:
                if "cap" in query_lower or "hat" in query_lower:
                    attributes["headwear"] = f"{color} cap"
                elif "shirt" in query_lower:
                    attributes["clothing"] = f"{color} shirt"
                elif "jacket" in query_lower:
                    attributes["clothing"] = f"{color} jacket"
                else:
                    attributes["color"] = color
        
        # Objects/accessories
        if "backpack" in query_lower or "bag" in query_lower:
            attributes["accessory"] = "backpack"
        if "glasses" in query_lower:
            attributes["accessory"] = "glasses"
        if "mask" in query_lower:
            attributes["accessory"] = "mask"
        
        # Location context
        spatial_constraints = {}
        if "entrance" in query_lower:
            spatial_constraints["location"] = "entrance"
        elif "checkout" in query_lower or "counter" in query_lower:
            spatial_constraints["location"] = "checkout"
        elif "near" in query_lower:
            spatial_constraints["proximity"] = "near"
        
        # Determine actions based on query
        actions = [ActionType.SEARCH_TEXT]  # Always start with text search
        
        if attributes:
            actions.append(ActionType.SEARCH_EMBEDDINGS)  # Visual search for attributes
        
        actions.extend([
            ActionType.BUILD_TIMELINE,
            ActionType.RETRIEVE_CLIPS
        ])
        
        # Add movement analysis if location mentioned
        if spatial_constraints:
            actions.append(ActionType.ANALYZE_MOVEMENT)
        
        return SearchPlan(
            query_type="person_search",
            primary_object="person",
            attributes=attributes,
            temporal_constraints={},
            spatial_constraints=spatial_constraints,
            actions=actions,
            confidence=0.85,
            reasoning=f"Person search query with attributes: {attributes}"
        )
    
    def _parse_time_query(self, original_query: str, query_lower: str, context: Optional[Dict]) -> SearchPlan:
        """Parse time-based queries"""
        
        temporal_constraints = {}
        
        # Extract time references
        if "after 5" in query_lower or "after 5pm" in query_lower:
            temporal_constraints["start_time"] = "17:00"
        elif "before 9" in query_lower or "before 9am" in query_lower:
            temporal_constraints["end_time"] = "09:00"
        elif "between" in query_lower:
            # This would need more sophisticated parsing in production
            temporal_constraints["time_range"] = "custom"
        
        actions = [
            ActionType.SEARCH_TIME_RANGE,
            ActionType.BUILD_TIMELINE,
            ActionType.RETRIEVE_CLIPS
        ]
        
        return SearchPlan(
            query_type="time_search",
            primary_object="events",
            attributes={},
            temporal_constraints=temporal_constraints,
            spatial_constraints={},
            actions=actions,
            confidence=0.90,
            reasoning="Time-based search for events within specified time range"
        )
    
    def _parse_duration_query(self, original_query: str, query_lower: str, context: Optional[Dict]) -> SearchPlan:
        """Parse duration-based queries"""
        
        attributes = {"duration_filter": True}
        
        # Extract duration
        if "2 minutes" in query_lower:
            attributes["min_duration_seconds"] = 120
        elif "1 minute" in query_lower:
            attributes["min_duration_seconds"] = 60
        elif "30 seconds" in query_lower:
            attributes["min_duration_seconds"] = 30
        
        actions = [
            ActionType.TRACK_DURATION,
            ActionType.BUILD_TIMELINE,
            ActionType.RETRIEVE_CLIPS
        ]
        
        return SearchPlan(
            query_type="duration_search",
            primary_object="tracks",
            attributes=attributes,
            temporal_constraints={},
            spatial_constraints={},
            actions=actions,
            confidence=0.80,
            reasoning="Duration-based search for tracks meeting time criteria"
        )
    
    def _parse_movement_query(self, original_query: str, query_lower: str, context: Optional[Dict]) -> SearchPlan:
        """Parse movement-based queries"""
        
        attributes = {}
        if "entered" in query_lower:
            attributes["movement_type"] = "entrance"
        elif "exited" in query_lower:
            attributes["movement_type"] = "exit"
        elif "moved" in query_lower:
            attributes["movement_type"] = "movement"
        
        actions = [
            ActionType.SEARCH_EVENTS,
            ActionType.ANALYZE_MOVEMENT,
            ActionType.BUILD_TIMELINE,
            ActionType.RETRIEVE_CLIPS
        ]
        
        return SearchPlan(
            query_type="movement_search",
            primary_object="events",
            attributes=attributes,
            temporal_constraints={},
            spatial_constraints={},
            actions=actions,
            confidence=0.75,
            reasoning="Movement-based search for entry/exit events"
        )
    
    def _parse_counting_query(self, original_query: str, query_lower: str, context: Optional[Dict]) -> SearchPlan:
        """Parse counting queries"""
        
        attributes = {"count_mode": True}
        
        if "people" in query_lower or "persons" in query_lower:
            attributes["count_object"] = "person"
        elif "tracks" in query_lower:
            attributes["count_object"] = "tracks"
        elif "events" in query_lower:
            attributes["count_object"] = "events"
        
        actions = [
            ActionType.COUNT_OBJECTS,
            ActionType.BUILD_TIMELINE
        ]
        
        return SearchPlan(
            query_type="counting_search",
            primary_object=attributes.get("count_object", "objects"),
            attributes=attributes,
            temporal_constraints={},
            spatial_constraints={},
            actions=actions,
            confidence=0.95,
            reasoning="Counting query for statistical analysis"
        )
    
    def _parse_general_query(self, original_query: str, query_lower: str, context: Optional[Dict]) -> SearchPlan:
        """Parse general/fallback queries"""
        
        actions = [
            ActionType.SEARCH_TEXT,
            ActionType.BUILD_TIMELINE,
            ActionType.RETRIEVE_CLIPS
        ]
        
        return SearchPlan(
            query_type="general_search",
            primary_object="general",
            attributes={"search_term": original_query},
            temporal_constraints={},
            spatial_constraints={},
            actions=actions,
            confidence=0.60,
            reasoning="General search using text similarity"
        )
    
    def _real_llm_parse(self, user_query: str, context: Optional[Dict] = None) -> SearchPlan:
        """
        Real LLM implementation using Gemini API
        
        Args:
            user_query: User's natural language query
            context: Optional context
            
        Returns:
            Structured search plan from LLM
        """
        from backend.core.config import settings
        import json
        
        try:
            from google import genai
            from google.genai import types
        except ImportError:
            logger.error("google-genai package not found. Falling back to mock LLM.")
            return self._mock_llm_parse(user_query, context)
            
        if not settings.GEMINI_API_KEY:
            logger.warning("GEMINI_API_KEY not set. Falling back to mock LLM.")
            return self._mock_llm_parse(user_query, context)
            
        client = genai.Client(api_key=settings.GEMINI_API_KEY)
        
        system_prompt = """
        You are an AI assistant for a video surveillance system. 
        Parse user queries into structured search plans.
        
        Available actions:
        - search_embeddings: Visual similarity search
        - search_events: Search event database
        - search_text: Text-based search
        - search_time_range: Time-based filtering
        - build_timeline: Generate timeline
        - retrieve_clips: Get video clips
        - analyze_movement: Movement analysis
        - find_similar: Find similar appearances
        - count_objects: Count/statistics
        - track_duration: Duration analysis
        
        Return ONLY valid JSON matching this schema:
        {
          "query_type": "person_search|time_search|duration_search|movement_search|counting_search|general_search",
          "primary_object": "person|events|tracks|general",
          "attributes": {"key": "value"},
          "temporal_constraints": {"start_time": "...", "end_time": "..."},
          "spatial_constraints": {"location": "...", "proximity": "..."},
          "actions": ["search_embeddings", "build_timeline", "retrieve_clips"],
          "confidence": 0.85,
          "reasoning": "Brief explanation of the plan"
        }
        """
        
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=user_query,
                config=types.GenerateContentConfig(
                    system_instruction=system_prompt,
                    response_mime_type="application/json",
                    temperature=0.1
                )
            )
            
            plan_dict = json.loads(response.text)
            
            # Map action strings to ActionType enums
            actions = []
            for act_str in plan_dict.get("actions", []):
                try:
                    actions.append(ActionType(act_str))
                except ValueError:
                    pass # ignore invalid actions
                    
            if not actions:
                actions = [ActionType.SEARCH_TEXT, ActionType.BUILD_TIMELINE]
                
            return SearchPlan(
                query_type=plan_dict.get("query_type", "general_search"),
                primary_object=plan_dict.get("primary_object", "general"),
                attributes=plan_dict.get("attributes", {}),
                temporal_constraints=plan_dict.get("temporal_constraints", {}),
                spatial_constraints=plan_dict.get("spatial_constraints", {}),
                actions=actions,
                confidence=float(plan_dict.get("confidence", 0.6)),
                reasoning=plan_dict.get("reasoning", "Parsed by Gemini API")
            )
        except Exception as e:
            logger.error(f"Error calling Gemini API: {e}. Falling back to mock LLM.")
            return self._mock_llm_parse(user_query, context)
    
    def _load_query_templates(self) -> Dict[str, Any]:
        """Load query templates for pattern matching"""
        return {
            "person_queries": [
                "find person wearing {color} {item}",
                "show me the {adjective} person",
                "locate person with {accessory}"
            ],
            "time_queries": [
                "show everyone who entered after {time}",
                "find events between {start_time} and {end_time}",
                "what happened before {time}"
            ],
            "duration_queries": [
                "people who stayed for more than {duration}",
                "tracks longer than {duration}",
                "show brief appearances"
            ],
            "movement_queries": [
                "who entered the {location}",
                "track movement from {location} to {location}",
                "analyze walking patterns"
            ],
            "counting_queries": [
                "how many people",
                "count the number of",
                "statistics for"
            ]
        }
    
    def explain_plan(self, plan: SearchPlan) -> str:
        """
        Generate human-readable explanation of the search plan
        
        Args:
            plan: SearchPlan to explain
            
        Returns:
            Human-readable explanation
        """
        explanation = f"🤖 AI Analysis: {plan.reasoning}\n\n"
        explanation += f"🎯 Search Type: {plan.query_type.replace('_', ' ').title()}\n"
        explanation += f"🎪 Primary Focus: {plan.primary_object.title()}\n"
        
        if plan.attributes:
            explanation += f"🏷️  Attributes: {', '.join(f'{k}: {v}' for k, v in plan.attributes.items())}\n"
        
        if plan.temporal_constraints:
            explanation += f"⏰ Time Constraints: {', '.join(f'{k}: {v}' for k, v in plan.temporal_constraints.items())}\n"
        
        if plan.spatial_constraints:
            explanation += f"📍 Location Constraints: {', '.join(f'{k}: {v}' for k, v in plan.spatial_constraints.items())}\n"
        
        explanation += f"\n🔧 Execution Plan:\n"
        for i, action in enumerate(plan.actions, 1):
            action_name = action.value.replace('_', ' ').title()
            explanation += f"   {i}. {action_name}\n"
        
        explanation += f"\n🎯 Confidence: {plan.confidence:.1%}"
        
        return explanation