"""
Phase 17 - Search Orchestrator ⭐⭐⭐⭐⭐

The LLM should never call database code directly.

Instead:
Prompt → LLM → Search Orchestrator → Embedding Search → Timeline Search → 
Event Search → Clip Service → Merge Results → Return JSON

This keeps the LLM isolated from your data layer.
"""

import logging
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional, Union
from sqlalchemy.orm import Session

from services.llm_intelligence import LLMIntelligence, SearchPlan, ActionType
from services.search_service import SearchService
from services.timeline_builder import TimelineBuilder
from services.clip_service import ClipService
from services.investigation_service_advanced import InvestigationService
from database.models.video import Video
from database.models.track import Track
from database.models.event import Event
from database.models.description import Description

logger = logging.getLogger(__name__)


class SearchOrchestrator:
    """
    Orchestrates search operations based on LLM-generated plans.
    
    The orchestrator:
    1. Receives structured plans from LLM
    2. Executes each action in the plan
    3. Coordinates multiple search services
    4. Merges results intelligently
    5. Never exposes database layer to LLM
    """
    
    def __init__(self, use_mock_llm: bool = True):
        """Initialize search orchestrator with all required services"""
        self.llm_intelligence = LLMIntelligence(use_mock_llm=use_mock_llm)
        self.search_service = SearchService()
        self.timeline_builder = TimelineBuilder()
        self.clip_service = ClipService()
        self.investigation_service = InvestigationService()
        
        logger.info("🎼 Search Orchestrator initialized")
    
    def execute_natural_language_query(
        self, 
        user_query: str, 
        db: Session,
        context: Optional[Dict] = None,
        max_results: int = 50
    ) -> Dict[str, Any]:
        """
        Execute natural language query end-to-end
        
        Args:
            user_query: Natural language query from user
            db: Database session
            context: Optional context (video_id, camera_id, etc.)
            max_results: Maximum results to return
            
        Returns:
            Comprehensive search results
        """
        logger.info(f"🎼 Executing natural language query: '{user_query}'")
        
        try:
            # Step 1: Parse query with LLM
            search_plan = self.llm_intelligence.parse_query(user_query, context)
            
            # Step 2: Execute the plan
            results = self.execute_search_plan(search_plan, db, context, max_results)
            
            # Step 3: Add LLM explanation to results
            results['llm_analysis'] = {
                'original_query': user_query,
                'plan_explanation': self.llm_intelligence.explain_plan(search_plan),
                'confidence': search_plan.confidence,
                'query_type': search_plan.query_type
            }
            
            logger.info(f"✅ Natural language query completed: {len(results.get('results', []))} results")
            return results
            
        except Exception as e:
            logger.error(f"❌ Natural language query failed: {e}")
            return {
                'status': 'error',
                'error': f'Query execution failed: {str(e)}',
                'original_query': user_query,
                'timestamp': datetime.now().isoformat()
            }
    
    def execute_search_plan(
        self,
        plan: SearchPlan,
        db: Session,
        context: Optional[Dict] = None,
        max_results: int = 50
    ) -> Dict[str, Any]:
        """
        Execute a structured search plan
        
        Args:
            plan: SearchPlan generated by LLM
            db: Database session
            context: Optional context
            max_results: Maximum results to return
            
        Returns:
            Orchestrated search results
        """
        logger.info(f"🎼 Executing search plan: {plan.query_type}")
        
        # Initialize result container
        orchestrated_results = {
            'plan_type': plan.query_type,
            'primary_object': plan.primary_object,
            'attributes': plan.attributes,
            'actions_executed': [],
            'results': [],
            'timeline': [],
            'clips': [],
            'statistics': {},
            'related_tracks': [],
            'status': 'success',
            'timestamp': datetime.now().isoformat()
        }
        
        try:
            # Execute each action in the plan
            for action in plan.actions:
                logger.info(f"🔧 Executing action: {action.value}")
                
                if action == ActionType.SEARCH_TEXT:
                    text_results = self._execute_text_search(plan, db, context, max_results)
                    orchestrated_results['results'].extend(text_results)
                    
                elif action == ActionType.SEARCH_EMBEDDINGS:
                    embedding_results = self._execute_embedding_search(plan, db, context, max_results)
                    orchestrated_results['results'].extend(embedding_results)
                    
                elif action == ActionType.SEARCH_EVENTS:
                    event_results = self._execute_event_search(plan, db, context, max_results)
                    orchestrated_results['results'].extend(event_results)
                    
                elif action == ActionType.SEARCH_TIME_RANGE:
                    time_results = self._execute_time_search(plan, db, context, max_results)
                    orchestrated_results['results'].extend(time_results)
                    
                elif action == ActionType.BUILD_TIMELINE:
                    timeline = self._build_timeline(orchestrated_results['results'], db)
                    orchestrated_results['timeline'] = timeline
                    
                elif action == ActionType.RETRIEVE_CLIPS:
                    clips = self._retrieve_clips(orchestrated_results['results'][:10], db)
                    orchestrated_results['clips'] = clips
                    
                elif action == ActionType.ANALYZE_MOVEMENT:
                    movement_analysis = self._analyze_movement(orchestrated_results['results'], db)
                    orchestrated_results['movement_analysis'] = movement_analysis
                    
                elif action == ActionType.FIND_SIMILAR:
                    similar_tracks = self._find_similar_tracks(orchestrated_results['results'], db)
                    orchestrated_results['related_tracks'] = similar_tracks
                    
                elif action == ActionType.COUNT_OBJECTS:
                    statistics = self._count_objects(plan, db, context)
                    orchestrated_results['statistics'] = statistics
                    
                elif action == ActionType.TRACK_DURATION:
                    duration_results = self._filter_by_duration(plan, db, context, max_results)
                    orchestrated_results['results'].extend(duration_results)
                
                orchestrated_results['actions_executed'].append(action.value)
            
            # Remove duplicates and sort results
            orchestrated_results['results'] = self._deduplicate_and_rank_results(
                orchestrated_results['results']
            )
            
            # Generate summary statistics
            orchestrated_results['summary'] = self._generate_summary(orchestrated_results)
            
            logger.info(f"✅ Search plan executed: {len(orchestrated_results['results'])} results")
            return orchestrated_results
            
        except Exception as e:
            logger.error(f"❌ Search plan execution failed: {e}")
            orchestrated_results['status'] = 'error'
            orchestrated_results['error'] = str(e)
            return orchestrated_results
    
    def _execute_text_search(
        self, 
        plan: SearchPlan, 
        db: Session, 
        context: Optional[Dict], 
        max_results: int
    ) -> List[Dict[str, Any]]:
        """Execute text-based search"""
        
        # Build search query from plan attributes
        search_terms = []
        
        if 'headwear' in plan.attributes:
            search_terms.append(plan.attributes['headwear'])
        if 'clothing' in plan.attributes:
            search_terms.append(plan.attributes['clothing'])
        if 'accessory' in plan.attributes:
            search_terms.append(plan.attributes['accessory'])
        if 'color' in plan.attributes:
            search_terms.append(plan.attributes['color'])
        if 'search_term' in plan.attributes:
            search_terms.append(plan.attributes['search_term'])
        
        search_query = ' '.join(search_terms) if search_terms else 'person'
        
        # Execute text search
        try:
            results = self.search_service.text_search(search_query, db, max_results)
            return [self._format_search_result(r, 'text_search') for r in results]
        except Exception as e:
            logger.error(f"Text search failed: {e}")
            return []
    
    def _execute_embedding_search(
        self, 
        plan: SearchPlan, 
        db: Session, 
        context: Optional[Dict], 
        max_results: int
    ) -> List[Dict[str, Any]]:
        """Execute embedding-based visual search"""
        
        # For mock implementation, simulate embedding search results
        # In production, this would use actual Re-ID embeddings
        
        mock_results = [
            {
                'result_type': 'embedding_match',
                'track_id': f'track_{i}',
                'similarity': 0.9 - (i * 0.1),
                'timestamp': (datetime.now() - timedelta(hours=i)).isoformat(),
                'attributes': plan.attributes,
                'source': 'visual_similarity'
            }
            for i in range(min(5, max_results))
        ]
        
        return mock_results
    
    def _execute_event_search(
        self, 
        plan: SearchPlan, 
        db: Session, 
        context: Optional[Dict], 
        max_results: int
    ) -> List[Dict[str, Any]]:
        """Execute event-based search"""
        
        # Build event query based on plan
        event_filters = {}
        
        if 'movement_type' in plan.attributes:
            movement_type = plan.attributes['movement_type']
            if movement_type == 'entrance':
                event_filters['event_type'] = 'track_started'
            elif movement_type == 'exit':
                event_filters['event_type'] = 'track_ended'
            else:
                event_filters['event_type'] = 'track_updated'
        
        # Query events
        query = db.query(Event)
        
        if 'event_type' in event_filters:
            query = query.filter(Event.event_type == event_filters['event_type'])
        
        if context and 'video_id' in context:
            query = query.filter(Event.video_id == context['video_id'])
        
        events = query.order_by(Event.timestamp.desc()).limit(max_results).all()
        
        return [
            {
                'result_type': 'event_match',
                'event_id': str(event.id),
                'track_id': str(event.track_id) if event.track_id else None,
                'event_type': event.event_type,
                'timestamp': event.timestamp.isoformat(),
                'confidence': event.score or 0.8,
                'source': 'event_search'
            }
            for event in events
        ]
    
    def _execute_time_search(
        self, 
        plan: SearchPlan, 
        db: Session, 
        context: Optional[Dict], 
        max_results: int
    ) -> List[Dict[str, Any]]:
        """Execute time-based search"""
        
        # Parse temporal constraints
        start_time = None
        end_time = None
        
        if 'start_time' in plan.temporal_constraints:
            # Parse time like "17:00" to today at that time
            time_str = plan.temporal_constraints['start_time']
            today = datetime.now().date()
            start_time = datetime.combine(today, datetime.strptime(time_str, '%H:%M').time())
        
        if 'end_time' in plan.temporal_constraints:
            time_str = plan.temporal_constraints['end_time']
            today = datetime.now().date()
            end_time = datetime.combine(today, datetime.strptime(time_str, '%H:%M').time())
        
        # Query events in time range
        query = db.query(Event)
        
        if start_time:
            query = query.filter(Event.timestamp >= start_time)
        if end_time:
            query = query.filter(Event.timestamp <= end_time)
        
        if context and 'video_id' in context:
            query = query.filter(Event.video_id == context['video_id'])
        
        events = query.order_by(Event.timestamp.asc()).limit(max_results).all()
        
        return [
            {
                'result_type': 'time_match',
                'event_id': str(event.id),
                'track_id': str(event.track_id) if event.track_id else None,
                'timestamp': event.timestamp.isoformat(),
                'event_type': event.event_type,
                'source': 'time_search'
            }
            for event in events
        ]
    
    def _filter_by_duration(
        self, 
        plan: SearchPlan, 
        db: Session, 
        context: Optional[Dict], 
        max_results: int
    ) -> List[Dict[str, Any]]:
        """Filter tracks by duration"""
        
        min_duration = plan.attributes.get('min_duration_seconds', 60)
        
        # Get tracks and calculate durations
        query = db.query(Track)
        
        if context and 'video_id' in context:
            query = query.filter(Track.video_id == context['video_id'])
        
        tracks = query.all()
        
        duration_results = []
        for track in tracks:
            if track.last_seen and track.first_seen:
                duration = (track.last_seen - track.first_seen).total_seconds()
                if duration >= min_duration:
                    duration_results.append({
                        'result_type': 'duration_match',
                        'track_id': str(track.id),
                        'duration_seconds': duration,
                        'first_seen': track.first_seen.isoformat(),
                        'last_seen': track.last_seen.isoformat(),
                        'source': 'duration_filter'
                    })
        
        # Sort by duration (longest first)
        duration_results.sort(key=lambda x: x['duration_seconds'], reverse=True)
        
        return duration_results[:max_results]
    
    def _count_objects(
        self, 
        plan: SearchPlan, 
        db: Session, 
        context: Optional[Dict]
    ) -> Dict[str, Any]:
        """Count objects based on plan"""
        
        count_object = plan.attributes.get('count_object', 'person')
        
        statistics = {}
        
        if count_object == 'person' or count_object == 'tracks':
            query = db.query(Track)
            if context and 'video_id' in context:
                query = query.filter(Track.video_id == context['video_id'])
            statistics['total_tracks'] = query.count()
            
        if count_object == 'events':
            query = db.query(Event)
            if context and 'video_id' in context:
                query = query.filter(Event.video_id == context['video_id'])
            statistics['total_events'] = query.count()
            
            # Count by event type
            event_types = db.query(Event.event_type, db.func.count(Event.id)).group_by(Event.event_type).all()
            statistics['events_by_type'] = {event_type: count for event_type, count in event_types}
        
        return statistics
    
    def _build_timeline(self, results: List[Dict], db: Session) -> List[Dict[str, Any]]:
        """Build timeline from search results"""
        # Extract unique event IDs from results
        event_ids = [result['event_id'] for result in results if 'event_id' in result]
        if event_ids:
            events = db.query(Event).filter(Event.id.in_(event_ids)).order_by(Event.timestamp.asc()).all()
            return self.timeline_builder.build_events_timeline(events)

        description_ids = [result['description_id'] for result in results if 'description_id' in result]
        if description_ids:
            descriptions = db.query(Description).filter(Description.id.in_(description_ids)).order_by(Description.timestamp.asc()).all()
            timeline = []
            for desc in descriptions:
                timeline.append({
                    'time': desc.timestamp.strftime('%H:%M:%S') if desc.timestamp else None,
                    'timestamp': desc.timestamp.isoformat() if desc.timestamp else None,
                    'event_type': 'description_match',
                    'track_id': str(desc.track_id) if desc.track_id else None,
                    'description': desc.description,
                    'confidence': desc.confidence,
                    'metadata': desc.desc_metadata or {},
                })
            return timeline

        return []
    
    def _retrieve_clips(self, results: List[Dict], db: Session) -> List[Dict[str, Any]]:
        """Retrieve clips for search results"""
        clips = []
        for result in results[:5]:  # Limit to top 5 results
            if 'event_id' in result:
                try:
                    clip_info = self.clip_service.extract_clip(result['event_id'], db)
                    clips.append(clip_info)
                except Exception as e:
                    logger.warning(f"Failed to extract clip for event {result['event_id']}: {e}")
        return clips
    
    def _format_search_result(self, result: Any, result_type: str) -> Dict[str, Any]:
        """Format search result for consistent output"""
        return {
            'result_type': result_type,
            'data': result,
            'timestamp': datetime.now().isoformat(),
            'source': result_type
        }
    
    def _deduplicate_and_rank_results(self, results: List[Dict]) -> List[Dict]:
        """Remove duplicates and rank results by relevance"""
        # Simple deduplication by track_id
        seen_tracks = set()
        deduplicated = []
        
        for result in results:
            track_id = result.get('track_id')
            if track_id and track_id in seen_tracks:
                continue
            if track_id:
                seen_tracks.add(track_id)
            deduplicated.append(result)
        
        # Sort by confidence/similarity if available
        def get_confidence(result):
            return result.get('similarity', result.get('confidence', 0.5))
        
        deduplicated.sort(key=get_confidence, reverse=True)
        
        return deduplicated
    
    def _generate_summary(self, orchestrated_results: Dict) -> Dict[str, Any]:
        """Generate summary of orchestrated results"""
        return {
            'total_results': len(orchestrated_results['results']),
            'unique_tracks': len(set(r.get('track_id') for r in orchestrated_results['results'] if r.get('track_id'))),
            'timeline_entries': len(orchestrated_results['timeline']),
            'clips_available': len(orchestrated_results['clips']),
            'actions_executed': len(orchestrated_results['actions_executed']),
            'execution_time': datetime.now().isoformat()
        }
    
    # Placeholder methods for missing implementations
    def _analyze_movement(self, results: List[Dict], db: Session) -> Dict[str, Any]:
        """Analyze movement patterns from results"""
        return {'analysis': 'Movement analysis not yet implemented'}
    
    def _find_similar_tracks(self, results: List[Dict], db: Session) -> List[Dict]:
        """Find similar tracks using Re-ID"""
        return []  # Placeholder